CREATE TABLE IF NOT EXISTS "user" (
    id int generated by default as identity,
    nickname varchar(50) not null,
    email varchar(200) not null,
    password varchar(200) not null,
    primary key(id)
);